[tool.black]
# code formatter
target-version = ["py36", "py37", "py38", "py39"]

[tool.isort]
# isort used for organizing imports in alphabetically order
profile = "black"
line_length = 100
lines_between_sections = 1
known_first_party = "sentry"
skip = "migrations"

[tool.mypy]
ignore_missing_imports = true