version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/python:3.9.12
    working_directory: ~/project

prepare_tox: &prepare_tox
  run:
    name: Installing tox
    command: |
      pip install --user tox

jobs:
  test-app:
    executor: my-custom-executor
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Test app
          command: |
            tox
  
  deploy-app:
    executor: my-custom-executor
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Deploy app to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

  deploy-app-container:
    executor: my-custom-executor
    steps:
      - setup_remote_docker:
          version: 20.10.17
      - checkout:
          path: ~/project
      - run:
          name: Build Docker Image
          command: |
            # download heroku cli and execute it
            sudo curl https://cli-assets.heroku.com/install.sh | sh 
            echo $(ls)
            make build-ml-api-heroku
      - run:
          name: Push image to Heroku Registry
          command: |
            make push-ml-api-heroku
      - run:
          name: Release to Heroku
          command: |
            make release-ml-api-heroku

workflows:
  my-custom-workflow:
    jobs:
      # - test-app
      # - deploy-app:
      #     requires:
      #     - test-app
      #     filters:
      #       branches:
      #         only:
      #           - main
      - deploy-app-container:
          filters:
            branches:
              only:
                - main
      